// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBDmhuVSeQBJ4q_03yQEQCUZdVi8m5_ezs',
    appId: '1:683506438037:web:51f1bc1c9d7cbe2320b09c',
    messagingSenderId: '683506438037',
    projectId: 'ourchat-49550',
    authDomain: 'ourchat-49550.firebaseapp.com',
    storageBucket: 'ourchat-49550.appspot.com',
    measurementId: 'G-KZ2CJJHXL5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC__0oR4hZMQBs1K6iW_dwI9diBfkha5eU',
    appId: '1:683506438037:android:be5356d41882ae0d20b09c',
    messagingSenderId: '683506438037',
    projectId: 'ourchat-49550',
    storageBucket: 'ourchat-49550.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA7IAKhFToOuOiNlQqoiIxduHTg0gj45jk',
    appId: '1:683506438037:ios:11909ed04faf34d920b09c',
    messagingSenderId: '683506438037',
    projectId: 'ourchat-49550',
    storageBucket: 'ourchat-49550.appspot.com',
    iosClientId:
        '683506438037-bfvb4kdf0kqi3ltgv6vsbekvmki3ssbl.apps.googleusercontent.com',
    iosBundleId: 'com.example.ourchat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA7IAKhFToOuOiNlQqoiIxduHTg0gj45jk',
    appId: '1:683506438037:ios:17e988233e52f7ff20b09c',
    messagingSenderId: '683506438037',
    projectId: 'ourchat-49550',
    storageBucket: 'ourchat-49550.appspot.com',
    iosClientId:
        '683506438037-cpfh1lp2s1lnmeqalti2nvsi8de2n420.apps.googleusercontent.com',
    iosBundleId: 'com.example.ourchat.RunnerTests',
  );
}
